quiz_data = [
    {"question": "france-flag.jpg", "choices": ["Germany", "France", "Italy"], "answer": "France"},
    {"question": "spain.png", "choices": ["Greece", "Portugal", "Spain"], "answer": "Spain"},
    {"question": "ıtaly.png", "choices": ["Germany", "Italy", "Netherlands"], "answer": "Italy"},
    {"question": "united kingdom.png", "choices":["Germany", "United Kingdom", "Belgium"], "answer": "United Kingdom"},
    {"question": "sweden.png", "choices": ["Sweden", "Norway", "Finland"], "answer": "Sweden"},
    {"question": "denmark.png", "choices": ["Belgium", "Netherlands", "Denmark"], "answer": "Denmark"},
    {"question": "portugal.png", "choices": ["Portugal", "Spain", "Italy"], "answer": "Portugal"},
    {"question": "norway.png", "choices": ["Norway", "Sweden", "Finland"], "answer": "Norway"},
    {"question": "china.png", "choices": ["China", "Japan", "India"], "answer": "China"},
    {"question": "south kora.png", "choices":["South Korea", "Thailand", "Vietnam"], "answer": "South Korea"},
    {"question": "japan.png", "choices": ["Japan", "China", "South Korea"], "answer": "Japan"},
    {"question": "india.png", "choices": ["India", "Pakistan", "Bangladesh"], "answer": "India"},
    {"question": "thailand.png", "choices": ["Thailand", "Vietnam", "Indonesia"], "answer": "Thailand"},
    {"question": "saudi arabia.png", "choices": ["Saudi Arabia", "Iran", "Iraq"], "answer": "Saudi Arabia"},
    {"question": "south kora.png", "choices": ["South Korea", "Japan", "China"], "answer": "South Korea"},
    {"question": "malaysia.png", "choices": ["Malaysia", "Singapore", "Indonesia"], "answer": "Malaysia"},
    {"question": "palestine.png", "choices": ["Pakistan", "India", "Palestine"], "answer": "Palestine"},
    {"question": "ındonesia.png", "choices": ["Indonesia", "Thailand", "Vietnam"], "answer": "Indonesia"},
    {"question": "philippines.png", "choices": ["Philippines", "Vietnam", "Malaysia"], "answer": "Philippines"},
    {"question": "Singapore.png", "choices": ["Singapore", "Malaysia", "Thailand"], "answer": "Singapore"},
    {"question": "south africa.png", "choices": ["South Africa", "Nigeria", "Kenya"], "answer": "South Africa"},
    {"question": "egypt.png", "choices": ["Egypt", "Algeria", "Morocco"], "answer": "Egypt"},
    {"question": "Morocco.png", "choices": ["Morocco", "Algeria", "Tunisia"], "answer": "Morocco"},
    {"question": "ghana.png", "choices": ["Ghana", "Nigeria", "South Africa"], "answer": "Ghana"},
    {"question": "tanzania.png", "choices": ["Tanzania", "Kenya", "Uganda"], "answer": "Tanzania"},
    {"question": "brazil.png", "choices": ["Brazil", "Argentina", "Colombia"], "answer": "Brazil"},
    {"question": "bulgaria.png", "choices": ["United States", "Bulgaria", "Mexico"], "answer": "Bulgaria"},
    {"question": "canada.png", "choices": ["Canada", "United States", "Mexico"], "answer": "Canada"},
    {"question": "germany.png", "choices": ["Egypt", "Germany", "Canada"], "answer": "Germany"},
    {"question": "greenland.png", "choices": ["Greenland", "Dominican Republic", "France"], "answer": "Greenland"},
    {"question": "iceland.png", "choices": ["Jamaica", "Cuba", "Iceland"], "answer": "Iceland"},
    {"question": "india.png", "choices": ["India", "Dominican Republic", "Cuba"], "answer": "India"},
]

